services:
  order-service:
    build: .
    ports:
      - "3004:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=flexrestro
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=order_service
      - JWT_SECRET=your-secret-key
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - flexrestro

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=flexrestro
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flexrestro

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - flexrestro

volumes:
  postgres_data:

networks:
  flexrestro:
    driver: bridge
